/**
 * A curated collection of mindful prompts for the Daily Fuel notification system.
 * These are designed to be reflective, open-ended, and intentional.
 */
export const DAILY_PROMPTS = [
  "What is one small thing that went well yesterday?",
  "How can you be more kind to yourself today?",
  "What is a thought that has been fueling your mind lately?",
  "What are you most grateful for in this exact moment?",
  "Who is someone you appreciate but haven't told recently?",
  "What is one habit you'd like to cultivate this month?",
  "What does 'peace' look like to you today?",
  "How can you make someone else's day a little brighter today?",
  "What is a challenge you've overcome that you're proud of?",
  "What is one thing you can let go of to feel lighter?",
  "What does your ideal morning routine look like?",
  "What is the most beautiful thing you saw yesterday?",
  "What is a goal that feels exciting but slightly scary?",
  "How do you want to feel by the end of this day?",
  "What is a book or quote that shifted your perspective?",
  "What is one thing you want to learn this week?",
  "How can you create more space for silence today?",
  "What are three things that make you feel truly alive?",
  "What is a boundary you need to set for your own peace?",
  "If you could give your younger self one piece of advice, what would it be?",
  "What is a 'simple pleasure' you often overlook?",
  "How can you show up more authentically today?",
  "What is something you've been procrastinating on, and why?",
  "What does 'enough' mean to you right now?",
  "What is a mistake you've made that taught you something valuable?",
  "How do you recharge when your energy is low?",
  "What is one thing you're looking forward to this week?",
  "What is a question you've been asking yourself lately?",
  "How can you bring more playfulness into your day?",
  "What is one area of your life where you want to grow?",
  "What is a 'win' you've had recently, no matter how small?",
  "What is one thing you can do today to help your future self?",
  "What does 'success' feel like to you, beyond money or status?",
  "How can you practice more active listening today?",
  "What is a dream you've had recently that felt significant?",
  "What is one thing you'd change about your current environment?",
  "How can you express more gratitude for your body today?",
  "What is a conversation you've been avoiding but need to have?",
  "What does 'home' mean to you?",
  "What is a skill you've mastered that you're proud of?",
  "How can you be a better friend to someone today?",
  "What is one thing you can simplify in your life right now?",
  "What is a memory that always makes you smile?",
  "How do you want to be remembered by the people you meet today?",
  "What is one thing you've changed your mind about recently?",
  "What does 'community' look like to you?",
  "How can you bring more intentionality to your work today?",
  "What is a risk you're glad you took?",
  "What is one thing you'd do if you weren't afraid of failure?",
  "How can you be more present in your next conversation?",
  "What is a quality you admire in someone else?",
  "What is one thing you can do to improve your mental space today?",
  "What does 'freedom' feel like to you?",
  "What is a song that perfectly describes your current mood?",
  "How can you be more patient with yourself during growth?",
  "What is one thing you want to accomplish before the month ends?",
  "What is a lesson you've learned from a difficult situation?",
  "How can you make your physical space feel more peaceful?",
  "What is one thing you're curious about right now?",
  "What does 'strength' look like to you today?",
  "How can you practice more self-compassion when you slip up?",
  "What is a belief you hold that brings you comfort?",
  "What is one thing you can do to connect with nature today?",
  "How can you be more mindful of your energy levels today?",
  "What is a quote that has stayed with you for years?",
  "What is one thing you'd like to be known for?",
  "How can you bring more joy into your routine?",
  "What is a fear you've faced and conquered?",
  "What does 'rest' mean to you beyond sleep?",
  "How can you be more supportive of someone else's dreams?",
  "What is one thing you've achieved that you once thought was impossible?",
  "What is a question someone asked you that made you think deeply?",
  "How can you create more 'flow' in your day today?",
  "What is one thing you're grateful for about your career?",
  "What does 'bravery' look like in your daily life?",
  "How can you be more intentional with your digital time?",
  "What is a gift you've received that you'll always treasure?",
  "What is one thing you can do to improve your sleep quality?",
  "How can you be more open to new experiences today?",
  "What is a tradition you love and why?",
  "What is one thing you'd like to change about your habits?",
  "How can you bring more empathy into your interactions?",
  "What is a compliment you received that you'll never forget?",
  "What does 'purpose' feel like to you right now?",
  "How can you be more consistent with your reflections?",
  "What is one thing you can do to feel more grounded today?",
  "What is a place that makes you feel completely at peace?",
  "How can you celebrate your progress, no matter how small?",
  "What is one thing you've learned about yourself this year?",
  "How can you be more forgiving of others' mistakes?",
  "What is a passion you've rediscovered recently?",
  "What does 'authenticity' mean in your current season of life?",
  "How can you bring more creativity into your problem-solving?",
  "What is one thing you can do to feel more energized today?",
  "What is a legacy you'd like to leave behind?",
  "How can you be more mindful of the words you use today?",
  "What is one thing you've done recently that felt truly meaningful?",
  "What does 'love' look like in your friendships right now?",
  "How can you be more intentional with your leisure time?",
  "What is a question you wish people would ask you more often?",
  "How can you practice more stillness in a busy world?",
  "What is one thing you can do to feel more connected to others?",
  "What does 'growth' feel like to you in this moment?",
  "How can you be more courageous in expressing your needs?",
  "What is one thing you can do to make your home feel more 'you'?",
  "What is a piece of art that moved you recently?",
  "How can you bring more wonder into your daily life?"
];

/**
 * Returns a prompt based on the day of the year to ensure everyone
 * gets the same prompt on the same day.
 */
export function getPromptForToday() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  
  return DAILY_PROMPTS[dayOfYear % DAILY_PROMPTS.length];
}
